spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: Partha@6864

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  jpa.hibernate.ddl_auto: update

management:
  endpoints:
    web:
      exposure:
        include: "health, beans, metrics"
      base-path: "/management-dashboard"
  endpoint:
    health:
      show-details: always

server:
  port: 8080
  address: 127.0.0.1
